spring:
    application:
        name: mars
    data:
        mongodb:
            uri: mongodb://shin:1234@localhost:27017/mars
logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
        org.mongodb.driver: DEBUG